apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-job
spec:
  template:
    spec:
      containers:
      - name: scraper
        image: us-central1-docker.pkg.dev/jmacleod-42/car-finder-agent-repo/car-finder-scraper:v3
        imagePullPolicy: Always # Ensure the latest image is pulled
        env:
        - name: MARKETCHECK_API_KEY
          valueFrom:
            secretKeyRef:
              name: marketcheck-api-key
              key: key
        command: ["/bin/sh", "-c", "curl -v 'https://api.marketcheck.com/v2/search/car/active?api_key=$MARKETCHECK_API_KEY'"]
      restartPolicy: OnFailure
  backoffLimit: 0
